### ISSUE TITLE
ransac.Model doesnt exist

### ISSUE THREAD

**Issue by kurtwagner19** [romack77/vp-toolbox#1]
when I try to run the code below,

```
import cv2
import os
from vp import vp_finder
import os.path

for filen in os.listdir("../"):
    print(filen)
    if ".png" in filen:
        imgpath=str(os.path.abspath(filen))
        image = cv2.imread(imgpath)
        print(imgpath)
        vp_to_lines, outlier_lines = vp_finder.find_vanishing_points_in_image(image)
        for vp in vp_to_lines:
            print('Vanishing point found at: (%s, %s)' % (vp[0], vp[1]))
```

 it gives an error saying ransac doesn't have Model 

```
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from vp import vp_finder
  File "/home/USER/Desktop/horizon/vp-toolbox-master/vp/vp_finder.py", line 9, in <module>
    from vp import vp_ransac
  File "/home/USER/Desktop/horizon/vp-toolbox-master/vp/vp_ransac.py", line 8, in <module>
    class SegmentVPModel(ransac.Model):
AttributeError: module 'ransac' has no attribute 'Model'
```
Do you have any advice?

**Comment by Dobberzoon** [comment]
I had the same issue, make sure your (relative) imports are corrected. The custom ransac repo that is imported, is downloaded into dir ransac, with module ransac inside. If your running dir is `/User/project`, it will be in `/User/project/ransac/ransac`. So, you need to do `import ransac.ransac as ransac`. I hope this helps.
